name: Build and Deploy Node.js app to Azure Web App - azure-sample-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Set up Node.js'
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version

    - name: 'Install Dependencies'
      run: |
        npm install

    - name: 'Build the App'
      run: |
        npm run build  # Use 'npm run build' if your project has a build step, otherwise, use 'npm start'

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azure-smaple-app'  # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
